### DISCUSSION TITLE
Expansion of Author Field

### DISCUSSION THREAD

**Discussion by austinsonger** [SigmaHQ/sigma#1992] [Ideas]
What you think of this idea, or if you have your own input, be greatly appreciative.  

Instead of just a author field like this `author:`

and add two fields for different types of authors

```
originating.author:
contributing.author:
```

- `originating.author` - the author (or authors) where the rule idea started from
- `contributing.author` - any contributors that comes afterwards that improves the rule from its original state.

**Comment by frack113** [comment]
I like the idea
Why not
```yaml
author: (optional)
  original: str as it is the writer (need if author )
  contributor: str or list (optinal)
```
