### DISCUSSION TITLE
Support needed for detection of creating new process using stolen access token T1134.002

### DISCUSSION THREAD

**Discussion by Jackson-Pollock** [SigmaHQ/sigma#2147] [Ideas]
Attack script: https://github.com/PowerShellMafia/PowerSploit/blob/master/Exfiltration/Invoke-TokenManipulation.ps1
Any idea how to detect token manipulation?

**Comment by austinsonger** [comment]
You want a detection create from the script?

**Reply by Jackson-Pollock** [reply]
No I added that script for attack reference if anyone wants to know the attack in short. I posted this to get ideas on the detection as I couldn't figured it out.

**Reply by austinsonger** [reply]
Your best bet is to fork and attempt to work on a detection and create a pull request so then contributors can review it and get you input.

**Comment by Neo23x0** [comment]
The usual procedure to get to a rule is:
- setup a lab environment 
- set a good audit policy and Sysmon configuration
- run the attack 
- Look at the logs and try to find log entries that are unique to that type of attack
- Write a rule to detect these log entries

**Reply by Jackson-Pollock** [reply]
Hi @Neo23x0 
Thanks for your reply!
I follow the same process, But specifically for this case (T1134.002) I need to observe behavior of WinAPI calls `DuplicateToken(Ex)` and `CreateProcessWithTokenW` and the relevant logs are not getting generated by Sysmon (Except Process access event 10: noisy and false positive) So I thought let's ask someone who can give suggestions.

**Comment by frack113** [comment]
just run some cmd for the help in a VM  but not seem to work (no error or output)
```yaml 
logsource:
    product: windows
    category: ps_module
    definition: PowerShell Module Logging must be enabled
detection:
    selection:
        Payload|contains: 'Invoke-TokenManipulation'
    condition: selection
```
```yaml
logsource:
    product: windows
    category: ps_script
    definition: Script block logging must be enabled
detection:
    selection:
        ScriptBlockText|contains: 'Invoke-TokenManipulation'
    condition: selection
```
