### DISCUSSION TITLE
Add generic/windows-services.yml

### DISCUSSION THREAD

**Discussion by frack113** [SigmaHQ/sigma#2564] [Ideas]
Hello,
To keep up to date all the backend mapping for windows log is awful (#2553)
I would like to change  to the actual way for windows rule to 
![image](https://user-images.githubusercontent.com/62423083/149614180-d074e744-a9ee-42ae-b576-3d20ab535520.png)

windows-services.yml have only a `logsources` section and a order of 15
`generic/powershell.yml` is now in windows-services.yml (no more 2 powershell.yml 😄 )

powershell2.yml
```yaml
title: Logsource to LogName mappings for PowerShell backend
order: 20
backends:
  - powershell
fieldmappings:
    Channel: LogName
```
winlogbeat-modules-enabled2.yml
```yaml
title: Elastic Winlogbeat (from 7.x) index pattern and field mapping following Elastic enabled Modules
order: 20
backends:
  - es-qs
  - es-dsl
  - es-rule
  - es-rule-eql
  - es-eql
  - kibana
  - kibana-ndjson
  - xpack-watcher
  - elastalert
  - elastalert-dsl
  - ee-outliers
defaultindex: winlogbeat-*
fieldmappings:
    EventID: event.code
...
````

![image](https://user-images.githubusercontent.com/62423083/149614392-fcc299b5-3923-4a0a-b40d-e452a252c38c.png)
