### DISCUSSION TITLE
Linux Authentication Failure - Playbook Help

### DISCUSSION THREAD

**Discussion by Mav1814** [SigmaHQ/sigma#4562] [Q&A] [answered]
Hi again. 

After reading the documentation suggested by @nasbench  and doing a few examples, I managed to create a playbook for windows to send alerts when authentication fails.

Now I'm trying to replicate it for Linux. I've tried several ways, and I still can't generate alerts.  

The sigma playbook is converted into an elasticsearch query.  But for some reason I can't get this information from kibana when I run the playbook and try to generate the alert. But if I put the result of the query into kibana, I get the desired result.

Two examples of the sigma playbook. 

```
title: Linux Authentication Failure
id: 4589aefa-7e55-11ee-b962-0242ac120002
status: test
description: Detects authentication failure in linux
author: mav1814
logsource:
    product: linux
    service: auth
detection:
    selection:
        message: 
            - "authentication failure"
    condition: selection
falsepositives:
    - Unknown
level: high
```
And 

```
title: Linux Authentication Failure
id: 4589aefa-7e55-11ee-b962-0242ac120002
status: test
description: Detects authentication failure in linux
author: mav1814
logsource:
    product: linux
    service: auth
detection:
    keywords:
            - "authentication failure"
    condition: keywords
falsepositives:
    - Unknown
level: high
```
I don't know what I'm missing here. 

I appreciate some insights/help. 
Cheers
