### ISSUE TITLE
issue with rule sysmon_creation_system_file and elasticsearch

### ISSUE THREAD

**Issue by 239487230597507** [SigmaHQ/sigma#1379]
Hello,

I am currently experimenting with sigma queries against our elasticsearch backend.  
After some testing I noticed that the rule sysmon_creation_system_file creates false positives.
It seems to be an issue with the elasticsearch backend when the selection and filter use the same field.

I have added the following to the rule itself (add directory to filter):

```
title: File Created with System Process Name
id: d5866ddf-ce8f-4aea-b28e-d96485a20d3d
status: experimental
description: Detects the creation of a executable with a system process name in a suspicious folder
author: Sander Wiebing
date: 2020/05/26
modified: 2020/08/23
tags:
    - attack.defense_evasion
    - attack.t1036          # an old one
    - attack.t1036.005
logsource:
    category: file_event
    product: windows
detection:
    selection:
        TargetFilename:
            - '*\svchost.exe'
            - '*\rundll32.exe'
            - '*\services.exe'
            - '*\powershell.exe'
            - '*\regsvr32.exe'
            - '*\spoolsv.exe'
            - '*\lsass.exe'
            - '*\smss.exe'
            - '*\csrss.exe'
            - '*\conhost.exe'
            - '*\wininit.exe'
            - '*\lsm.exe'
            - '*\winlogon.exe'
            - '*\explorer.exe'
            - '*\taskhost.exe'
            - '*\Taskmgr.exe'
            - '*\taskmgr.exe'
            - '*\sihost.exe'
            - '*\RuntimeBroker.exe'
            - '*\runtimebroker.exe'
            - '*\smartscreen.exe'
            - '*\dllhost.exe'
            - '*\audiodg.exe'
            - '*\wlanext.exe'
    filter:
        TargetFilename:
            - 'C:\Windows\System32\\*'
            - 'C:\Windows\system32\\*'
            - 'C:\Windows\SysWow64\\*'
            - 'C:\Windows\SysWOW64\\*'
            - 'C:\Windows\winsxs\\*'
            - 'C:\Windows\WinSxS\\*'
            - 'C:\Windows\SoftwareDistribution\\*'  <-------- added
            - '\SystemRoot\System32\\*'
    condition: selection and not filter
fields:
    - Image
falsepositives:
    - System processes copied outside the default folder
level: high

```
The Problem is that I am getting hits with this TargetFilename:
```
C:\\Windows\\SoftwareDistribution\\Download\\e8f82696fdd18cb4375990feaf4b3648\\inst\\amd64_microsoft-windows-smartscreen_31bf3856ad364e35_10.0.14393.4169_none_3323e2d87ab1c64a\\smartscreen.exe
```

This is the query I got from the converter:
```
{
  "query": {
    "constant_score": {
      "filter": {
        "bool": {
          "must": [
            {
              "match_phrase": {
                "Channel": "Microsoft-Windows-Sysmon/Operational"
              }
            },
            {
              "bool": {
                "should": [
                  {
                    "wildcard": {
                      "TargetFilename.keyword": "*\\\\svchost.exe"
                    }
                  },
                  {
                    "wildcard": {
                      "TargetFilename.keyword": "*\\\\rundll32.exe"
                    }
                  },
                  {
                    "wildcard": {
                      "TargetFilename.keyword": "*\\\\services.exe"
                    }
                  },
                  {
                    "wildcard": {
                      "TargetFilename.keyword": "*\\\\powershell.exe"
                    }
                  },
                  {
                    "wildcard": {
                      "TargetFilename.keyword": "*\\\\regsvr32.exe"
                    }
                  },
                  {
                    "wildcard": {
                      "TargetFilename.keyword": "*\\\\spoolsv.exe"
                    }
                  },
                  {
                    "wildcard": {
                      "TargetFilename.keyword": "*\\\\lsass.exe"
                    }
                  },
                  {
                    "wildcard": {
                      "TargetFilename.keyword": "*\\\\smss.exe"
                    }
                  },
                  {
                    "wildcard": {
                      "TargetFilename.keyword": "*\\\\csrss.exe"
                    }
                  },
                  {
                    "wildcard": {
                      "TargetFilename.keyword": "*\\\\conhost.exe"
                    }
                  },
                  {
                    "wildcard": {
                      "TargetFilename.keyword": "*\\\\wininit.exe"
                    }
                  },
                  {
                    "wildcard": {
                      "TargetFilename.keyword": "*\\\\lsm.exe"
                    }
                  },
                  {
                    "wildcard": {
                      "TargetFilename.keyword": "*\\\\winlogon.exe"
                    }
                  },
                  {
                    "wildcard": {
                      "TargetFilename.keyword": "*\\\\explorer.exe"
                    }
                  },
                  {
                    "wildcard": {
                      "TargetFilename.keyword": "*\\\\taskhost.exe"
                    }
                  },
                  {
                    "wildcard": {
                      "TargetFilename.keyword": "*\\\\Taskmgr.exe"
                    }
                  },
                  {
                    "wildcard": {
                      "TargetFilename.keyword": "*\\\\taskmgr.exe"
                    }
                  },
                  {
                    "wildcard": {
                      "TargetFilename.keyword": "*\\\\sihost.exe"
                    }
                  },
                  {
                    "wildcard": {
                      "TargetFilename.keyword": "*\\\\RuntimeBroker.exe"
                    }
                  },
                  {
                    "wildcard": {
                      "TargetFilename.keyword": "*\\\\runtimebroker.exe"
                    }
                  },
                  {
                    "wildcard": {
                      "TargetFilename.keyword": "*\\\\smartscreen.exe"
                    }
                  },
                  {
                    "wildcard": {
                      "TargetFilename.keyword": "*\\\\dllhost.exe"
                    }
                  },
                  {
                    "wildcard": {
                      "TargetFilename.keyword": "*\\\\audiodg.exe"
                    }
                  },
                  {
                    "wildcard": {
                      "TargetFilename.keyword": "*\\\\wlanext.exe"
                    }
                  }
                ]
              }
            },
            {
              "bool": {
                "must_not": [
                  {
                    "bool": {
                      "must": [
                        {
                          "bool": {
                            "should": [
                              {
                                "wildcard": {
                                  "TargetFilename.keyword": "C:\\\\Windows\\\\System32\\\\*"
                                }
                              },
                              {
                                "wildcard": {
                                  "TargetFilename.keyword": "C:\\\\Windows\\\\system32\\\\*"
                                }
                              },
                              {
                                "wildcard": {
                                  "TargetFilename.keyword": "C:\\\\Windows\\\\SysWow64\\\\*"
                                }
                              },
                              {
                                "wildcard": {
                                  "TargetFilename.keyword": "C:\\\\Windows\\\\SysWOW64\\\\*"
                                }
                              },
                              {
                                "wildcard": {
                                  "TargetFilename.keyword": "C:\\\\Windows\\\\winsxs\\\\*"
                                }
                              },
                              {
                                "wildcard": {
                                  "TargetFilename.keyword": "C:\\\\Windows\\\\WinSxS\\\\*"
                                }
                              },
                              {
                                "wildcard": {
                                  "TargetFilename.keyword": "C:\\\\Windows\\\\SoftwareDistribution\\\\*"
                                }
                              },
                              {
                                "wildcard": {
                                  "TargetFilename.keyword": "\\\\SystemRoot\\\\System32\\\\*"
                                }
                              }
                            ]
                          }
                        }
                      ]
                    }
                  }
                ]
              }
            }
          ]
        }
      }
    }
  },
  "_source": [
    "Image"
  ]
}
```

Any input would be welcome!
Thanks and regards
