### ISSUE TITLE
Generic logsource but with Sysmon specific key-value pairs

### ISSUE THREAD

**Issue by washal** [SigmaHQ/sigma#1427]
Taking an example of the rule https://github.com/SigmaHQ/sigma/blob/master/rules/windows/registry_event/sysmon_comhijack_sdclt.yml

The log-source is defined generically as 'registry_event'
However, if we are to run this with Windows native event - 4657, then it would not work.
The event ID 4657 does not have any field called EventType or something similar which would have the value 'SetValue'

This defeats the purpose of having generic log sources.
I understand the filename mentions 'sysmon' but I don't think we should take that into consideration when running conversion.

Is my understanding incorrect ? Was generic logsources intended to be used in this manner?

I think the correct rule definition would be

```
logsource:
    category: registry_event
    product: windows
    service: sysmon
detection:
   selection:
      EventID:  13
```
