### ISSUE TITLE
Support for distinct_count Aggregation

### ISSUE THREAD

**Issue by d4rk-d4nph3** [SigmaHQ/sigma#1591]
It would be better if there was support for _distinct_count_ aggregation which is required for certain UseCases.

One example is detecting a burst of DNS requests in a small timeframe to distinct domains having uncommon TLDs from the same source which is seen in activities of C2.

#### Example usage

```yaml
logsource:
    category: dns
detection:
    selection:    
        timeframe: 1m
        query|endswith:
            - '.online'
            - '.download'
            - '.space'
            - '.uno'
            - '.top'
    condition: selection | distinct_count() by src_ip > 4
```

If there is a way to do this without _distinct_count_ then let me know.
