### ISSUE TITLE
[ALA] Convesion of wildcard not as expected for ala backend.

### ISSUE THREAD

**Issue by denny-lclin** [SigmaHQ/sigma#1689]
Sigma:

 ```
...
detection:
    rule1:
        detectionname|contains:          
            - 'trickbot'
    condition: rule1
...
```
or
```
...
detection:
    rule1:
        detectionname:          
            - '*trickbot*'
    condition: rule1
...
```

Expected output:
```
My_Table | where (detectionname contains 'trickbot')
```

Actual output: 
```
My_Table | where (detectionname contains '.*trickbot.*')
```
which is not able to search for 'trickbot' in column *detectionname*
