### ISSUE TITLE
Length Function for Fields

### ISSUE THREAD

**Issue by zhantt1** [SigmaHQ/sigma#1862]
I wish to create a sigma rule for DNS tunneling targeting DNS queries that are greater than a particular length. Is there a length function to capture this information?

For example:
```
logsource:
  product: sysmon
detection:
  selection:
    EventID: 22
    QueryName: '*'
  condition: selection | length(QueryName) >= SOME_VALUE
```

**Comment by frack113** [comment]
Hi,
one fast solution 
```yaml
logsource:
  product: windows
  category: dns_query
detection:
  selection:
    QueryName|re: '.{SOME_VALUE,}'
  condition: selection
````
