### ISSUE TITLE
Clarify AWS Update Login Profile rule

### ISSUE THREAD

**Issue by rachelrice** [SigmaHQ/sigma#1966]
The [AWS CloudTrail Update Login Profile](https://github.com/SigmaHQ/sigma/blob/master/rules/cloud/aws/aws_update_login_profile.yml) rule has detection section:
```
    selection_source:
        eventSource: iam.amazonaws.com
        eventName: UpdateLoginProfile
    filter:
        userIdentity.arn|contains: responseElements.accessKey.userName
    condition: selection_source and not filter
```

So it is looking for event where `source = iam.amazonaws.com`, `name = UpdateLoginProfile` and `userIdentity.arn does not contain responseElements.accessKey.userName`.

When an `UpdateLoginProfile` event is caused via AWS CLI e.g. `aws iam update-login-profile --user-name xxx --password yyy`, the resulting CloudTrail event looks like:
```
    "userIdentity": {
        "type": "IAMUser",
        "principalId": "xxx,
        "arn": "arn:aws:iam::xxx:user/xxx",
        "accountId": "xxx",
        "accessKeyId": "xxx",
        "userName": "xxx"
    },
    "eventSource": "iam.amazonaws.com",
    "eventName": "UpdateLoginProfile",
    "requestParameters": {
        "userName": "xxx"
    },
    "responseElements": null,
```

Suggest the rule detection selection be updated to:
```
    selection_source:
        eventSource: iam.amazonaws.com
        eventName: UpdateLoginProfile
    filter:
        userIdentity.arn|contains: requestParameters.userName
    condition: selection_source and not filter
```
