### ISSUE TITLE
registry_event_cve_2021_31979_cve_2021_33771_exploits.yml

### ISSUE THREAD

**Issue by frack113** [SigmaHQ/sigma#2088]
HI,
This rule looking for the keyword IMJPUEXP.DLL.

When I read the references and make some test on registry with sysmon:
- HKEY_LOCAL_MACHINE\SOFTWARE\Classes\ is HKCR\ on sysmon EventID 13
- for default value TargetObject end with (Default)
- value must end with system32\wbem\wmiutils.dll or system32\wbem\wbemsvc.dll

So detection can be convert to
```yaml
selection:
   TargetObject|endswith:
      - CLSID\{CF4CC405-E2C5-4DDD-B3CE-5E7582D8C9FA}\InprocServer32\(Default)
      - CLSID\{7C857801-7381-11CF-884D-00AA004B2E24}\InProcServer32\(Default)
filter:
   Details|endswith:
       - system32\wbem\wmiutils.dll
       - system32\wbem\wbemsvc.dll
condition: selection and not filter
```

If someone can try the cve to validate the rule or send me the evtx.
Thanks
