### ISSUE TITLE
Sigma Rule Condition Spec: Logical AND vs. each-of

### ISSUE THREAD

**Issue by hazedav** [SigmaHQ/sigma#2143]
A few Sigma rules have been recently introduced which have some interesting conditions:
https://github.com/SigmaHQ/sigma/blob/master/rules/cloud/aws/aws_pass_role_to_lambda_function.yml
https://github.com/SigmaHQ/sigma/blob/master/rules/cloud/aws/passed_role_to_glue_development_endpoint.yml

```
detection:
    selection1:
        eventSource: iam.amazonaws.com
        eventName: PassRole
    selection2:
        eventSource: lambda.amazonaws.com
        eventName: CreateFunction
    selection3:
        eventSource: lambda.amazonaws.com
        eventName: InvokeFunction
    condition: selection1 and selection2 and selection3
```

The condition statement here seems to imply that the Sigma backend should logically AND selection1/selection2/selection3.  However, each selection contains a unique eventSource/eventName combination...  It is not possible that a single CloudTrail event take on more than a single eventSource/eventName value.  Not speaking for author @austinsonger but it seems like the intention here is that we want "each of" these selections.

In "psuedosearch" this would be the difference between:
`(eventSource=A AND eventName=X) AND (eventSource=B AND eventName=Y) AND (eventSource=B AND eventName=Z)`

versus

`(eventSource=A AND eventName=X) OR (eventSource=B AND eventName=Y) OR (eventSource=B AND eventName=Z) | eventstats distinct_count(eventName) as distinct_eventName_count | where distinct_eventName_count=3`

After reading the Wiki section on Specification conditions a few times it was unclear how a rule author would communicate "each of"
https://github.com/SigmaHQ/sigma/wiki/Specification#condition

Please advise.
Thanks,
David
