### ISSUE TITLE
Logsource index mapping random

### ISSUE THREAD

**Issue by frack113** [SigmaHQ/sigma#2156]
Hi,
my colleague has found a funny way of working when choosing the index
the index mapping test
```yaml
  auditd:
    service: auditd
    product: linux
    index: auditd-*
  linux:
    product: linux
    index: linux-*
```
the command : 
`python sigmac -t elastalert -c config\generic\sysmon.yml -c config\test.yml ..\rules\linux\auditd\lnx_auditd_alter_bash_profile.yml`

Get sometime `auditd` and other time `linux`

I have dug class SigmaLogsourceConfiguration in `sigma/tools/sigma/configuration.py`
I think it is the matches func but  I'm drowning
