### ISSUE TITLE
CarbonBlack Back end truncates spaces from sigma rules

### ISSUE THREAD

**Issue by remotephone** [SigmaHQ/sigma#2292]
See https://github.com/SigmaHQ/sigma/pull/2291 whether it's merged or not, the conversion to carbonblack from a generic sigma rule removes trailing spaces. This is probably fine most of the time, but if we're explicitly looking for spaces it could cause problems.

Example:
```
tools/sigmac --target carbonblack rules/linux/macos/process_creation/macos_space_after_filename.yml -c carbon-black
(cmdline:"" OR ImageName:"")
```
I thought maybe the problem was here - https://github.com/SigmaHQ/sigma/blob/bac2e9f35e61ecd6410c108e4779264d4f668233/tools/sigma/backends/carbonblack.py#L159 - but I don't think so since I tried using `'* '` and `'e* '` and got the same result.

**Comment by nasbench** [comment]
Hi and thanks for opening this issue. 

I did some tests and the issue seems to be located in the function you mentioned.

Here are a couple of examples:

```yml
detection:
    selection1:
        CommandLine|endswith: 'e* '
    selection2:
        ImageName|endswith: ' s'
```

Would generate

```bash
(cmdline:e OR ImageName:s)
```

and

```yml
detection:
    selection1:
        CommandLine|endswith: 'e* '
    selection2:
        ImageName|endswith: ' '
```

Would generate

```bash
(cmdline:e OR ImageName:"")
```

The fix would be to remove the usage of `isspace` since we assume that any character (even if it's a space) is an **intended** part of the detection and we cannot trim it.
