### ISSUE TITLE
FP win_lateral_movement_condrv

### ISSUE THREAD

**Issue by frack113** [SigmaHQ/sigma#2411]
Hi,
From lab , get many FP so would like to add 
```yml
filter:
   PrivilegeList: SeSecurityPrivilege
   ProcessName: "C:\Windows\System32\cmd.exe"
```
Any advice ?
