### ISSUE TITLE
sysmon_new_dll_added_to_appinit_dlls_registry_key logging policy error

### ISSUE THREAD

**Issue by tcmcgahanred** [SigmaHQ/sigma#2521]
sysmon_new_dll_added_to_appinit_dlls_registry_key calls for filtering sysmon EID 13 "NewName" with "Details", but I believe that isn't possible.

![image](https://user-images.githubusercontent.com/67395486/148258225-548c5d2d-b2be-4ac9-9f12-cb12a2417492.png)

In order for this configuration to validate, I had to remove the "NewName" grouping and only leave the "TargetObject" grouping.

![image](https://user-images.githubusercontent.com/67395486/148258535-4f9e66b9-6ede-4ffe-be36-2b75c4027c36.png)

sysmon does not allow for the filtering of "NewName" with "Details" unfortunately. 

![image](https://user-images.githubusercontent.com/67395486/148258780-d2a1a39d-c654-4588-8f2d-2a6fbc5c86b9.png)

Is there a work around here to meet the intent of the rule?

**Comment by tcmcgahanred** [comment]
@redsand 

Great work but have a question for you here. Many thanks!

**Comment by redsand** [comment]
What version of sysmon are you running?  Might be a newer field and you're behind.

**Comment by frack113** [comment]
Find this in SwiftOnSecurity sysmonconfig-export.xml:
`<!--TECHNICAL:	You cannot filter on the "Details" attribute, due to performance issues when very large keys are written, and variety of data formats-->`

But filter will never work on `NewName` 
```yml
detection:
    selection_rename:
        NewName|endswith:
                - '\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Windows\AppInit_Dlls'
                - '\SOFTWARE\Wow6432Node\Microsoft\Windows NT\CurrentVersion\Windows\AppInit_Dlls'
    selection_set:
       TargetObject|endswith:
                - '\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Windows\AppInit_Dlls'
                - '\SOFTWARE\Wow6432Node\Microsoft\Windows NT\CurrentVersion\Windows\AppInit_Dlls'
    filter_set:
      Details: '(Empty)'
    condition: selection_rename or selection_set and not filter_set
```

**Comment by tcmcgahanred** [comment]
This was tested on v13.31

**Comment by redsand** [comment]
Sorry to hear that...  These rules are applied insided our SIEM/MDR platform and are not filtered using sysmon.

**Comment by redsand** [comment]
https://docs.microsoft.com/en-us/answers/questions/332062/sysmon-help-im-unable-to-filter-on-eid-13-data-nam.html

**Comment by redsand** [comment]
One idea would be to modify the tools/sigma/backends/sysmon.py and filter out any keys with Details

**Comment by tcmcgahanred** [comment]
I was the one that reported that bug :) , but it was fixed with a patch, but I'm thinking it's been broken once again.

https://docs.microsoft.com/en-us/answers/questions/332062/sysmon-help-im-unable-to-filter-on-eid-13-data-nam.html

**Comment by redsand** [comment]
hahaha, small world!

**Comment by tcmcgahanred** [comment]
lol yes it is.

The fact is though that you can only combine "TargetObject" and "Details" under EID 13. "NewName" does not allow for filtering of "Details".

I had to make the rule look like thus:

```
detection:
  selection:
    EventID:
    - 13
    TargetObject|endswith:
    - '\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Windows\AppInit_Dlls'
    - '\SOFTWARE\Wow6432Node\Microsoft\Windows NT\CurrentVersion\Windows\AppInit_Dlls'
    filter:
      Details: 
      - ''
      - (Empty)
  condition: selection and not filter
splunk: index=os_windows_sysmon_* (EventCode="13" (TargetObject="*\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Windows\\AppInit_Dlls" OR TargetObject="*\\SOFTWARE\\Wow6432Node\\Microsoft\\Windows NT\\CurrentVersion\\Windows\\AppInit_Dlls") NOT (Details="" OR Details="(Empty)"))
```

And the conf entry as thus:

```
<Sysmon schemaversion="4.70">
	<EventFiltering>
	<RuleGroup name="" groupRelation="or">
		<RegistryEvent onmatch="include">
			<Rule groupRelation="and">		
				<TargetObject name="technique_id=AO.TA0003.T1546.010.001,technique_name=New DLL Added to AppInit_DLLs Registry Key" condition="end with">\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Windows\AppInit_Dlls</TargetObject>
				<Details name="technique_id=AO.TA0003.T1546.010.001,technique_name=New DLL Added to AppInit_DLLs Registry Key" condition="excludes">-</Details>
				<Details name="technique_id=AO.TA0003.T1546.010.001,technique_name=New DLL Added to AppInit_DLLs Registry Key" condition="excludes">(Empty)</Details>
			</Rule>
			<Rule groupRelation="and">		
				<TargetObject name="technique_id=AO.TA0003.T1546.010.001,technique_name=New DLL Added to AppInit_DLLs Registry Key" condition="end with">\SOFTWARE\Wow6432Node\Microsoft\Windows NT\CurrentVersion\Windows\AppInit_Dlls</TargetObject>
				<Details name="technique_id=AO.TA0003.T1546.010.001,technique_name=New DLL Added to AppInit_DLLs Registry Key" condition="excludes">-</Details>
				<Details name="technique_id=AO.TA0003.T1546.010.001,technique_name=New DLL Added to AppInit_DLLs Registry Key" condition="excludes">(Empty)</Details>			
			</Rule>
		</RegistryEvent>
	</RuleGroup>
</EventFiltering>
</Sysmon>
```

Until I find a work around.
