### ISSUE TITLE
Type modifier 're' is not supported by backend

### ISSUE THREAD

**Issue by cpkgstangs** [SigmaHQ/sigma#2633]
I have run into the following error on multiple rules, any idea how to fix it? 

`An unsupported feature is required for this Sigma rule (win_invoke_obfuscation_obfuscated_iex_services.yml): Type modifier 're' is not supported by backend`

Thanks

**Comment by frack113** [comment]
Hello,
What is your backend ?
The backend does not carry all the modifiers, `re` (regex) is the least supported.

**Comment by cpkgstangs** [comment]
New to this, I think that would be splunk. Here is one of the commands I ran that returned that message:
`sigmac -t splunk win_invoke_obfuscation_clip_services.yml --config splunk-windows`

**Comment by frack113** [comment]
Splunk backend converts Sigma rule into Splunk Search Processing Language.
Splunk can use [regex](https://docs.splunk.com/Documentation/Splunk/8.2.4/SearchReference/Regex) but need to be add it in the sigmac code (if possible of course).
So no easy solution to fix it.

**Comment by cpkgstangs** [comment]
I see it imported in splunk.py under backends. I guess that's for another use then? Thanks

**Comment by Neo23x0** [comment]
I'm in general no big fan of regex use, especially when it is absolutely unnecessary. 

e.g. in this case
```
logsource:
    product: windows
    service: security
detection:
    selection:
        Provider_Name: 'Service Control Manager'
        EventID: 4697
        ServiceFileName|re: '.*cmd.{0,5}(?:\/c|\/r).+clip(?:\.exe)?.{0,4}&&.+clipboard]::\(\s\\\"\{\d\}.+\-f.+\"'
```

I would bet 100$ that one could rewrite that rule like this (see below) without triggering a false positive in the next 100 years on 1 million systems in 100 different orgs: 

```
logsource:
    product: windows
    service: security
detection:
    selection:
        Provider_Name: 'Service Control Manager'
        EventID: 4697
        ServiceFileName|contains|all: 
           - 'cmd'
           - 'clip'
           - 'clipboard]::'
```

Regex ... I'd really like to work through all the regex expressions in our repo and get rid of them wherever possible. It's completely unnecessary in 50-70% of the cases.
