### ISSUE TITLE
Sigma Correlations: group by different fields

### ISSUE THREAD

**Issue by gaelmuller** [SigmaHQ/sigma#2842]
Hello, we are working on Sigma Correlations and have found that when correlating information from different sources, the `group-by` clause may not be complete.

Let's take an hypothetical example where we would like to detect a 500 error code in reverse proxy logs followed by a successful connection in the other direction. In this case, we would like to `group-by` IP address, except in one case it would be the source IP and the other the destination IP. Is there an officially supported way to do this ?

If not, I would propose the introduction of an `aliases` property to define which fields should be used:

```
name: internal_error
detection:
  selection:
    http.response.status_code: 500
  condition: selection
---
name: new_network_connection
detection:
  selection:
    event.category: network
    event.type: connection
    event.outcome: success
  condition: selection
---
action: correlation
type: temporal
rule:
  - internal_error
  - new_network_connection
group-by:
  - internal_ip
  - remote_ip
timespan: 10s
ordered: true
aliases:
  internal_ip:
    internal_error: destination.ip
    new_network_connection: source.ip
  remote_ip:
    internal_error: source.ip
    new_network_connection: destination.ip
```
