### ISSUE TITLE
Sysmon rules potentially overritten 

### ISSUE THREAD

**Issue by motazreda** [SigmaHQ/sigma#2874]
# rules selection logical bug in sysmon conversion #
it was discovered an issue when the user run the command sigmac with option sysmon to convert the YAML rules to sysmon config file format.
the issue is that when there is a search-identifier for example  "CommandLine|endswith" in the selection and the same search-identifier in another selection. it will overwrite the first selection search-identifier with the new one which as a result remove completely the first selection search-identifier rule.

for Example

### Rule
>rules/windows/process_creation/proc_creation_win_grabbing_sensitive_hives_via_reg.yml
```yaml
title: Grabbing Sensitive Hives via Reg Utility
id: fd877b94-9bb5-4191-bb25-d79cbd93c167
status: test
description: Dump sam, system or security hives using REG.exe utility
author: Teymur Kheirkhabarov, Endgame, JHasenbusch, Daniil Yugoslavskiy, oscd.community
references:
  - https://www.slideshare.net/heirhabarov/hunting-for-credentials-dumping-in-windows-environment
  - https://eqllib.readthedocs.io/en/latest/analytics/aed95fc6-5e3f-49dc-8b35-06508613f979.html
  - https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1003/T1003.md
  - https://www.wietzebeukema.nl/blog/windows-command-line-obfuscation
date: 2019/10/22
modified: 2021/11/27
logsource:
  category: process_creation
  product: windows
detection:
  selection_1:
    Image|endswith: '\reg.exe'
    CommandLine|contains:
      - 'save'
      - 'export'
      - 'ˢave'
      - 'eˣport'
  selection_2:
    CommandLine|contains:
      - 'hklm'
      - 'hk˪m'
      - 'hkey_local_machine'
      - 'hkey_˪ocal_machine'
      - 'hkey_loca˪_machine'
      - 'hkey_˪oca˪_machine'
  selection_3:
    CommandLine|endswith:
      - '\system'
      - '\sam'
      - '\security'
      - '\ˢystem'
      - '\syˢtem'
      - '\ˢyˢtem'
      - '\ˢam'
      - '\ˢecurity'
  condition: selection_1 and selection_2 and selection_3
falsepositives:
  - Dumping hives for legitimate purpouse i.e. backup or forensic investigation
level: medium
tags:
  - attack.credential_access
  - attack.t1003.002
  - attack.t1003.004
  - attack.t1003.005
  - car.2013-07-001
```
### Command to convert to sysmon
```bash
tools/sigmac -t sysmon -c sysmon rules/windows/process_creation/proc_creation_win_grabbing_sensitive_hives_via_reg.yml
```
### The result is
```xml
<!--RuleGroup groupRelation should be `or` <RuleGroup groupRelation="or"> -->

<!--Insert This Rule in <ProcessCreate onmatch="include"> section -->

		<Rule name="Grabbing Sensitive Hives via Reg Utility by Teymur Kheirkhabarov, Endgame, JHasenbusch, Daniil Yugoslavskiy, oscd.community" groupRelation="and">
			<Image condition="end with">\reg.exe</Image>
			<CommandLine condition="contains any">hklm;hk˪m;hkey_local_machine;hkey_˪ocal_machine;hkey_loca˪_machine;hkey_˪oca˪_machine</CommandLine>
			<CommandLine condition="contains any">\system;\sam;\security;\ˢystem;\syˢtem;\ˢyˢtem;\ˢam;\ˢecurity</CommandLine>
		</Rule>
```
When taking a closer look the selection 'selection_1' with search-identifier 'CommandLine|contains' has been completely ignored. That’s because it's being overridden with the same search-identifier in selection 'selection_2' with 'CommandLine|contains'.

now the first search-identifier in the selection_1 which was contains
```yaml
- 'save'
- 'export'
- 'ˢave'
- 'eˣport'
```
has been completely ignored.

now the snippet below is the cause of the issue
> /tools/sigma/backends/sysmon.py
```python
def createRuleGroup(self, condition_objects, condition, match_type="include"):
        rules = None
        rules_selections = [item for item in condition_objects if item.type == 4]
        if len(rules_selections) == 1:
            rule, table = self.createRule(self.detection.get(rules_selections[0].matched))
            rules = {match_type: {table: rule}}
        else:
            if "or" in condition.lower():
                result = {}
                for selection_object in rules_selections:
                    rule, table = self.createRule(self.detection.get(selection_object.matched))
                    if result.get(table):
                        result[table].append(rule)
                    else:
                        result[table] = [rule]
                result = {table_name: "\n\t\t".join(rules_list) for table_name, rules_list in result.items()}
                rules = {match_type: result}
            elif "and" in condition.lower():
                rules_dict = {}
                for selection_object in rules_selections:
                    rules_dict.update(self.detection.get(selection_object.matched))
                rule, table = self.createRule(rules_dict)
                rules = {match_type: {table: rule}}
        if rules:
            rules_result = []
            for match, tables in rules.items():
                for table, rules in tables.items():
                    category_comment = '\n<!--Insert This Rule in <{} onmatch="{}"> section -->\n{}'.format(table, match,
                                                                                                            "".join(rules))
                    rules_result.append(category_comment)
            return "".join(rules_result)
        else:
            raise NotSupportedError("Couldn't create rule with current condition.")
```

if you take a look at lines 'elif "and" in condition.lower():' you will find that it creates an empty "rules_dict = {}" dictionary for all search-identifier under all selections which assign a key name with the search-identifier, which is "CommandLine|contains" and the value is the values inside the search-identifier. now when there is the same search-identifier in another selection, the same key name will be overwritten
 with the new values inside new search-identifier with same key name.
