### ISSUE TITLE
Inconcrete win_codeintegrity_failed_driver_load.yml

### ISSUE THREAD

**Issue by b1t-hunter** [SigmaHQ/sigma#2919]
``This rule checks the entire CodeIntegrity channel for a string. The referenced text is specific to one event id only. The rule can be changed to the following more concrete version.

Current detection:
```
detection:
    keywords:
        - 'that did not meet the Microsoft signing level requirements'
    condition: keywords
```

Proposed detection:
```
detection:
    selection:
        EventID: 3076
        Requested Signing Level: Microsoft
    condition: selection
```
