### ISSUE TITLE
Reference Lookup Lists in Detection Logic

### ISSUE THREAD

**Issue by eiq-toliver** [SigmaHQ/sigma#3199]
Are there any intentions for SIGMA to support Lookup lists? I understand this was previously raised in https://github.com/SigmaHQ/sigma/issues/289 but I'm revisiting it as something to include in my SIGMA rules. 

I agree that for the most part matching against mass lists for the purpose of detection is not a great practice as atomic indicators tend to become less valuable over time. I have found that using named lookup lists can be very valuable in reducing false positives. The example below references a Lookup Table that my SIEM supports such as 'internal domains' which contains a list of internal domains, network blocks and descriptions. These can be used to ignore sightings that reference any internal domain.

```
title: Regsvr32 Network Activity
id: 36e037c4-c228-4866-b6a3-48eb292b9955
related:
    - id: c7e91a02-d771-4a6d-a700-42587e0b1095
      type: derived
description: Detects network connections and DNS queries initiated by Regsvr32.exe
references:
    - https://pentestlab.blog/2017/05/11/applocker-bypass-regsvr32/
    - https://oddvar.moe/2017/12/13/applocker-case-study-how-insecure-is-it-really-part-1/
    - https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1117/T1117.md
tags:
    - attack.execution
    - attack.t1559.001
    - attack.defense_evasion
    - attack.t1218.010
author: Dmitriy Lifanov, oscd.community
status: experimental
date: 2019/10/25
modified: 2021/09/21
logsource:
    category: dns_query
    product: windows
detection:
    selection:
        Image|endswith: '\regsvr32.exe'
    **internalLookup:
        QueryName: LOOKUP(InternalDomains)**
    condition: selection AND NOT internalLookup
fields:
    - ComputerName
    - User
    - Image
    - DestinationIp
    - DestinationPort
falsepositives:
    - Unknown
level: high
```

I suppose there is nothing stopping me putting this in the detection logic as is and using a modified compiler to generate the correct query on the backend. For reference, I'm currently building a platform that intends to support SIGMA as the native way to author detections and not expose some of the complexities of the datastore query language to the user so being able to inlcude other more complex logic. I was really glad to see the Correlations appear in March for example.
