### ISSUE TITLE
Sigma Modifier: list/reference set

### ISSUE THREAD

**Issue by Res260** [SigmaHQ/sigma#3540]
Some SIEMs, such as QRadar have the capacity to reference a value contained in a reference set (an internal list of values). 

Would a modifier like `inlist` make sense for sigma?

Something like:

```yaml
title: Test reg rule
id: 12345
status: stable
description: test rule
author: Someone
level: medium
logsource:
  product: Something
detection:
  selection:
    Filename|contains: 'reg.exe'
    commandLine|re: '(?i).*save.*(?:hklm|hkey_local_machine)\\\\system.*'
  exclusions:
    ParentBaseFileName|inlist: myExclusionsList
  condition: selection and not exclusions
```

I feel like there should be a way to be able to reference data outside of the rule. Does that make sense?
