### ISSUE TITLE
Undocumented rewrite in config files

### ISSUE THREAD

**Issue by herrBez** [SigmaHQ/sigma#404]
According to the [documentation of the configuration files](https://github.com/Neo23x0/sigma/wiki/Converter-Tool-Sigmac), there are only the following fields nested in logsources:

```yml
logsources:
  sigma_logsource:
    category: ...
    product: ...
    service: ...
    index:
      - target_indexname1
      - target_indexname2
    conditions:
      field1: value1
      field2: value2
```

However, file `tools/config/thor.yml` contains also the field "rewrite":

```yml
logsources:
  # log source configurations for generic sigma rules
  process_creation_1:
    category: process_creation
    product: windows
    conditions:
      EventID: 1
    rewrite:
      product: windows
      service: sysmon
```

What is the purpose of this additional field? Can we add it to the documentation?
