### ISSUE TITLE
Error in proc_creation_win_sdbinst_shim_persistence?

### ISSUE THREAD

**Issue by L015H4CK** [SigmaHQ/sigma#4306]
Hello again everyone,

this time I was looking into the [proc_creation_win_sdbinst_shim_persistence](https://github.com/SigmaHQ/sigma/blob/b02e3b698afbaae143ac4fb36236eb0b41122ed7/rules/windows/process_creation/proc_creation_win_sdbinst_shim_persistence.yml#L20) rule and found the following condition: `CommandLine|contains: '.sdb'`.

The [reference](https://www.mandiant.com/resources/blog/fin7-shim-databases-persistence) shows that FIN7 uses sdbinst to install a custom shim database with `.tmp` ending - so the rule would not trigger in that case. I spent some time digging deeper into the topic and found that you can indeed use sdbinst to install custom databases using files that do not have the `.sdb` ending, e.g. by saving them as `.tmp` file.

The rule does not specifically detect FIN7 behavior but "installation of a new shim using sdbinst.exe" in general. But since these installations are also possible using other files endings than `.sdb`, I propose the rule could/should be updated.

A possible solution is:
- remove `CommandLine|contains: '.sdb'` in the selection part
- (optional to remove false positives) add `-u` and `-?` to the filter to remove sdbinst.exe usage when uninstalling or printing the help page (see [documentation](https://learn.microsoft.com/en-us/windows/deployment/planning/using-the-sdbinstexe-command-line-tool))

```
detection:
    selection:
        Image|endswith: '\sdbinst.exe'
    filter:
        CommandLine|contains:
            - 'iisexpressshim.sdb' # normal behaviour for IIS Express (e.g. https://www.hybrid-analysis.com/sample/15d4ff941f77f7bdfc9dfb2399b7b952a0a2c860976ef3e835998ff4796e5e91?environmentId=120)
            - '-u' # uninstall
            - '-?' # help
    condition: selection and not filter
```

If my understanding of this rule is correct and my proposed solution seems fitted, I will gladly open a pull request.

Best regards,
Louis
