### ISSUE TITLE
Placeholder support 

### ISSUE THREAD

**Issue by 0xffca** [SigmaHQ/sigma#450]
I quite new to Sigma and I was not able to make placeholders work.

Searching through the previous issues I found that the issue [1] has been dropped. and that 
Placeholders are not supported by the converter [2].
However, since Placeholders are in the documentation [3] there has to be a way to use them. 
Has anyone successfully used this feature? 

Thanks!

[1] https://github.com/Neo23x0/sigma/issues/21
[2] https://github.com/Neo23x0/sigma/pull/217
[3] https://github.com/Neo23x0/sigma/wiki/Specification#placeholders

Here's what I did:
### Rule:
```
title: Service Installation
description: Detects new Windows services
logsource:
    product: windows
    service: system
detection:
    selection:
        EventID: 4697
    
    known_services: 
        ServiceFileName: '%known_services%'

    condition: selection and not known_services
falsepositives: []
level: low
```

### Configfile:
```
logsources:
  windows:
    product: windows
    index: windows_*

placeholders:
  known_services:
    - 'C:\Windows\System32\xxx.sys'
```

### Commanline:

`tools/sigmac -c winlogbeat -c ./tools/config/conftest.yml -t es-dsl ./testrule.yml`

### Result:
```
{
  "query": {
    "constant_score": {
      "filter": {
        "bool": {
          "must": [
            {
              "match_phrase": {
                "winlog.event_id": "4697"
              }
            },
            {
              "bool": {
                "must_not": [
                  {
                    "bool": {
                      "must": [
                        {
                          "match_phrase": {
                            "winlog.event_data.ServiceFileName": "%known_services%"
                          }
                        }
                      ]
                    }
                  }
                ]
              }
            }
          ]
        }
      }
    }
  }
}
```
### Expected Result:
```
{
  "query": {
    "constant_score": {
      "filter": {
        "bool": {
          "must": [
            {
              "match_phrase": {
                "winlog.event_id": "4697"
              }
            },
            {
              "bool": {
                "must_not": [
                  {
                    "bool": {
                      "must": [
                        {
                          "match_phrase": {
                            "winlog.event_data.ServiceFileName": "C:\Windows\System32\xxx.sys"
                          }
                        }
                      ]
                    }
                  }
                ]
              }
            }
          ]
        }
      }
    }
  }
}
```
