### ISSUE TITLE
Zeek Rule SMB Correction

### ISSUE THREAD

**Issue by forewarned** [SigmaHQ/sigma#763]
I believe the "name" and "path" fields are swapped in [sigma/rules/network/zeek/zeek_smb_converted_win_susp_psexec.yml](https://github.com/Neo23x0/sigma/blob/master/rules/network/zeek/zeek_smb_converted_win_susp_psexec.yml) under **detection >> selection1 and selection2**.

It should be:
```
detection:
    selection1:
        path: \\*\IPC$
        name:
         - '*-stdin'
         - '*-stdout'
         - '*-stderr'
    selection2:
        path: \\*\IPC$
        name: 'PSEXESVC*'
```

Examples of the correct fields in use:
https://github.com/richiercyrus/Bro-Scripts/blob/master/bad-share.bro (See Line 13 and 21)
https://holdmybeersecurity.com/2019/02/20/part-1-threat-hunting-with-bro-zeek-and-eql/ (See log in screenshot under "Detecting SMB lateral movement section")
