### ISSUE TITLE
[es-dsl] Is it possible to confirm the existence of the field?

### ISSUE THREAD

**Issue by tatsu-i** [SigmaHQ/sigma#777]
I have a question about creating a rule like

poc.yaml
```
title: Active Directory User Backdoors
logsource:
    product: windows
    service: security
detection:
    selection1:
        EventID: 4738
    filter1:
        AllowedToDelegateTo: 
            - null
            - '-'
    condition: (selection1 and not 1 of filter*)
```
ES DSL translates to
```
./sigmac -t es-dsl -c config/winlogbeat-modules-enabled.yml poc.yaml
{
  "query": {
    "constant_score": {
      "filter": {
        "bool": {
          "must": [
            {
              "match_phrase": {
                "winlog.channel": "Security"
              }
            },
            {
              "match_phrase": {
                "winlog.event_id": "4738"
              }
            },
            {
              "bool": {
                "must_not": [
                  {
                    "bool": {
                      "should": [
                        {
                          "bool": {
                            "must": [
                              {
                                "bool": {
                                  "should": [
                                    {
                                      "match_phrase": {
                                        "winlog.event_data.AllowedToDelegateTo": "None"
                                      }
                                    },
                                    {
                                      "match_phrase": {
                                        "winlog.event_data.AllowedToDelegateTo": "-"
                                      }
                                    }
                                  ]
                                }
                              }
                            ]
                          }
                        }
                      ]
                    }
                  }
                ]
              }
            }
          ]
        }
      }
    }
  }
}

```
Then the EventID is 4738 and all documents where AllowedToDelegateTo does not exist will be hit

Is there a way to output an ES-DSL that contains the following query?

```
{
    "query": {
        "exists": {
            "field": "winlog.event_data.AllowedToDelegateTo"
        }
    }
}
```

**Comment by Karneades** [comment]
Yes, using the "not null" operator, and in the ES backend it's ready for that case (if interested, see https://github.com/Neo23x0/sigma/blob/master/tools/sigma/backends/elasticsearch.py#L376)

Example rule for not null: https://github.com/Neo23x0/sigma/blob/master/rules/windows/process_creation/win_susp_svchost.yml

```
    filter_null:
        ParentImage: null
    condition: selection and not filter and not filter_null
```

**Comment by Karneades** [comment]
Yes, using the "not null" operator should work and in the ES backend it's ready for that case (if interested, see https://github.com/Neo23x0/sigma/blob/master/tools/sigma/backends/elasticsearch.py#L376)

Maybe try using only one value and the not exists has some issues with lists?

Example rule for not null: https://github.com/Neo23x0/sigma/blob/master/rules/windows/process_creation/win_susp_svchost.yml

``` yaml
    filter_null:
        ParentImage: null
    condition: selection and not filter and not filter_null
```

Example output for ES

```
((winlog.event_data.Image.keyword:*\\svchost.exe AND (NOT (winlog.event_data.ParentImage.keyword:(*\\services.exe OR *\\MsMpEng.exe OR *\\Mrt.exe OR *\\rpcnet.exe)))) AND (NOT (NOT _exists_:winlog.event_data.ParentImage)))
```

**Comment by tatsu-i** [comment]
Thank you very much!
By modifying as follows, the number of hits has been reduced to 0.
```
title: Active Directory User Backdoors
logsource:
    product: windows
    service: security
detection:
    selection1:
        EventID: 4738
    filter_null:
        AllowedToDelegateTo: null
    filter1:
        AllowedToDelegateTo: 
            - null
            - '-'
    condition: selection1 and not filter1 and not filter_null

```
