### ISSUE TITLE
[Backend][elastalert] Backend options for TheHive alerter 

### ISSUE THREAD

**Issue by architect00** [SigmaHQ/sigma#817]
## Problem
I want Elastalert to report matches to TheHive, but SIGMA does not provide configuration for this via the backend options. As far as I know only `email` and `http_post` are supported/implemented.

```python
           # ... OMITTED ...
           #Handle alert action
            rule_object['alert'] = []
            alert_methods = self.alert_methods.split(',')
            if 'email' in alert_methods:
                # ... OMITTED ...
            if 'http_post' in alert_methods:
               # ... OMITTED ...
```

## Proposal

Implementation of TheHive alerter options in _sigma/backends/elasticsearch.py_. According to [TheHive documentation](https://github.com/TheHive-Project/TheHiveDocs/blob/master/api/alert.md#model-definition) the following fields need to set to raise an alert:
```yaml
title: "Rulename"
type: "external"
source: "IDS"
sourceRef: "0ffe2391d" # ID for source reference (correlation)
description: "Hey forum, what's happening!"
severity: 2 # 1 - 3 (4 comming soon in TheHive 4)
tags: ['attack.initial_access', 'attack.t1091']
tlp: 3 # ['White' 0 , 'Green' 1 , 'Amber' 2 , 'Red' 3]
artifacts: # default=empty artifact list
status: "New" # ['New', 'Updated', 'Ignored', 'Imported']
follow: True
```

The following fields could be set in the backend option file, because they are static and might not change between different rules:
```
thehive_connection:
  thehive_host: https://thehive.your.soc
  thehive_port: 9000
  thehive_apikey: correct-horse-battery-staple
```

Some of those fields can be filled with data from the [SIGMA rule specification](https://github.com/Neo23x0/sigma/wiki/Specification) itself:
```yaml
title: sigma.title
type: sigma.logsource.type
sourceRef: sigma.id # optional; set by elastalert
description:
  - sigma.description
  - sigma.references
  - sigma.false-positives
tags: sigma.tags
severity: sigma.level
```

Since the SIGMA specification does allow custom fields, the following fields could be read from a sigma rule file:
```yaml
source: "IDS" # because it depends default=sigma.logsource.product
tlp: 3 # ['White' 0 , 'Green' 1 , 'Amber' 2 , 'Red' 3] default=2
status: "New" # ['New', 'Updated', 'Ignored', 'Imported'] default=New
follow: True # default=True
artifacts: # list of artifacts default empty
  - workstation_name: "{match[source.hostname]}"
```

I would volunteer to implement this functionality, if there are no major concerns (look at discussion).

## Discussion

Is SIGMA supposed provide such configuration of backend systems? 

On the other hand I understand, that these options might be subject to change in e.g. elastalert itself. Providing detailed backend configuration options could result in more maintenance effort to keep up with the supported backends.

In my opinion, this project is intended to enable users to switch between backends. Providing such backend configuration options would enhance the usability.

Any thoughts/concerns on this from you guys? Otherwise I get started with the implementation.

**Comment by frack113** [comment]
first try the output format seems correct. still to work on it now:
```YAML
D:\FrackSigma\Sigma\tools>python sigmac -t elastalert -c .\config\generic\sysmon.yml ..\rules\windows\sysmon\sysmon_accessing_winapi_in_powershell_credentials_dumping.yml --backend-option alert_methods=thehive
alert:
- hivealerter
description: Detects Accessing to lsass.exe by Powershell
filter:
- query:
    query_string:
      query: (EventID:("8" OR "10") AND SourceImage.keyword:*\\powershell.exe AND TargetImage.keyword:*\\lsass.exe)
hive_alert_config:
  description: '{match[field1]} {rule[name]} Sample description'
  follow: true
  severity: 2
  source: elastalert
  status: New
  tags:
  - tag1
  - tag2 {rule[name]}
  title: Title
  tlp: 3
  type: external
hive_connection:
  hive_proxies:
    http: ''
    https: ''
  thehive_apikey: correct-horse-battery-staple
  thehive_host: https://thehive.your.soc
  thehive_port: 9000
hive_observable_data_mapping:
- 'domain: "{match[field1]}_{rule[name]}"'
- 'domain: "{match[field]}"'
- 'ip: "{match[ip_field]}"'
index: logstash-*
name: 3f07b9d1-2082-4c56-9277-613a621983cc_0
priority: 2
realert:
  minutes: 0
type: any
```
