### ISSUE TITLE
rules/windows/sysmon/sysmon_cmstp_execution.yml duplicated to registry_event and process_access

### ISSUE THREAD

**Issue by rtkbkish** [SigmaHQ/sigma#887]
The rule CMSTP Execution is now in three locations:
rules/windows/sysmon/sysmon_cmstp_execution.yml
rules/windows/registry_event/sysmon_cmstp_execution.yml
rules/windows/process_access/sysmon_cmstp_execution.yml

While the original rule looks correct, the copies into the new category paths do not seem correct.

I would suggest something like:
```
---
logsource:
    category: registry_event
    product: windows
detection:
    selection1:
        TargetObject: '*\cmmgr32.exe*'
---
logsource:
    category: process_access
    product: windows
detection:
    # Process Access Call Trace
    selection1:
        CallTrace: '*cmlua.dll*'
---
logsource:
    category: process_creation
    product: windows
detection:
    # CMSTP Spawning Child Process
    selection1:
        ParentImage: '*\cmstp.exe'
```

Or revert to the original.
