### ISSUE TITLE
[Backend] Bug - Trailing wildcard dropped when contains/startswith transformation ends with escaped asterisk

### ISSUE THREAD

**Issue by acalarch** [SigmaHQ/sigma#955]
Example Rule: 

```yaml
detection:
    selection:
        field|contains: '\*'
    condition: selection
```
Becomes (elastic): `field.keyword:*\*`
Should be (elastic): `field.keyword:*\**`

Appears in splunk, qradar, etc backends as well.
